spring:
  datasource:
      loan:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/loan
        username: root
        password: Galata97


server:
  port: 8082
